services:
  app:
    image: kslupsky/docker-demo:v2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/messages
    depends_on:
      - db
    volumes:
      - ./app:/app
    command: sh -c "npm install && npm start"
    # networks:
    #   - appnet

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messages
    volumes:
      - pgdata:/var/lib/postgresql/data
    # networks:
    #   - appnet

volumes:
  pgdata:

# networks:
#   appnet:
#     driver: bridge